// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS0vG3cxrpd6O-jHJg_5gqsqnmydO2Dok',
    appId: '1:598242494589:android:f139adc19c2db51af1c914',
    messagingSenderId: '598242494589',
    projectId: 'goinggreen-ee212',
    databaseURL: 'https://goinggreen-ee212-default-rtdb.firebaseio.com',
    storageBucket: 'goinggreen-ee212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLkW-gpk5BgV5rb2IXAVdzXAtsL7XpkjQ',
    appId: '1:598242494589:ios:e59d6aa2137d447bf1c914',
    messagingSenderId: '598242494589',
    projectId: 'goinggreen-ee212',
    databaseURL: 'https://goinggreen-ee212-default-rtdb.firebaseio.com',
    storageBucket: 'goinggreen-ee212.appspot.com',
    androidClientId: '598242494589-69oth54ldl3b4369lu2brik293uatgn8.apps.googleusercontent.com',
    iosClientId: '598242494589-70lgbie4o1shs2h62i0ig56us3uvsj7q.apps.googleusercontent.com',
    iosBundleId: 'com.going.green.goingGreen',
  );
}
